### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-EvaMarco#1]
Really cool job, @evamarco !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Fix the language of the page

## CSS - box model
- [x] The footer should have a static position
- [x] You can distribute the total height of the browser between the main and de footer elements, or leave the 100% of the browser height to the main element and have a nice vertical scroll

## Good practices
- [x] Try to improve your commit messages, better in English and using imperative

Let me know if you have any doubts ;)

Go for it!!

**Comment by EvaMarco** [comment]
I think I fix everything you asked me. Please tell me if there is something more I can improve.
Thanks Eva.

**Comment by oneeyedman** [comment]
Well done @EvaMarco!

Here you have a cool gif!
![Well done](https://media.giphy.com/media/9g8PH1MbwTy4o/giphy.gif)
